service: ecommerce-inventory

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.lambda_handler
    events:
      - http:
          path: /products
          method: any

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux
